wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.3
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1710941314.77292
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      - 105
      3:
      - 23
      4: 3.11.5
      5: 0.16.3
      8:
      - 1
      - 5
      13: linux-x86_64
